//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.03 at 08:45:21 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demo.com/spring/soap/api/loanEligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.spring.soap.api.loaneligibility;
