//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.01 at 10:38:59 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.demo.com/spring/soap/api/loanEligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.spring.soap.api.loaneligibility;
